# Generated by Django 3.0.7 on 2020-09-11 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectManagement', '0004_auto_20200903_0702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-modified_at']},
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='sprint',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='state',
            new_name='status',
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=300, unique=True)),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('NOT', 'NOT OK')], default='OK', max_length=5)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
