# Generated by Django 3.0.7 on 2020-09-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0005_auto_20200911_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='comentaire',
            field=models.TextField(blank=True),
        ),
    ]
