# Generated by Django 3.0.7 on 2020-09-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0006_note_comentaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='comentaire',
            new_name='comment',
        ),
    ]
