# Generated by Django 3.0.7 on 2020-09-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0007_auto_20200911_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT', 'NOT OK')], default='OK', max_length=5),
        ),
    ]
