# Generated by Django 3.0.7 on 2020-09-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0010_auto_20200911_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('resolutionTools', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='projectManagement.Task')),
            ],
        ),
    ]
