# Generated by Django 3.0.7 on 2020-09-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0012_auto_20200920_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
