# Generated by Django 3.0.7 on 2020-09-22 11:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0014_auto_20200922_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 11, 33, 38, 722950, tzinfo=utc)),
        ),
    ]
