# Generated by Django 3.0.7 on 2020-09-22 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0015_auto_20200922_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
