# Generated by Django 3.0.7 on 2020-09-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0016_auto_20200922_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='cause',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('CLOTURE', 'CLOTURE'), ('NON_CLOTURE', 'NON_CLOTURE')], default='NON_CLOTURE', max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='resolutionTools',
            field=models.CharField(max_length=200),
        ),
    ]
