# Generated by Django 3.0.7 on 2020-10-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0018_auto_20200925_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['designation']},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(max_length=300),
        ),
    ]
