# Generated by Django 3.0.7 on 2020-10-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0019_auto_20201008_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
